export const langNameMappings: Record<string, string> = {
  ar: "Arabic",
  zh: "Simplified Chinese",
  zhtw: "Traditional Chinese",
  cs: "Czech",
  hr: "Croatian",
  da: "Danish",
  nl: "Dutch",
  el: "Greek",
  en: "English",
  en_US: "English (US)",
  fi: "Finnish",
  fr: "French",
  ga: "Irish",
  gl: "Galician",
  de: "German",
  hu: "Hungarian",
  it: "Italian",
  ja: "Japanese",
  ko: "Korean",
  nb_NO: "Norwegian Bokmål",
  pl: "Polish",
  pt: "Portuguese",
  pt_BR: "Portuguese (Brazil)",
  ru: "Russian",
  sk: "Slovak",
  sl: "Slovenian",
  es: "Spanish",
  sv: "Swedish",
  tr: "Turkish",
  uk: "Ukrainian",
  vi: "Vietnamese",
};

export const supportedLangs = Object.keys(langNameMappings);
