#
# IMPORTANT NOTE
#
# This chart inherits from the bjw-s library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
#

applicationProtocol: http
applicationHost: karakeep.domain
applicationSecretKey: ~
meilisearchMasterKey: ~

controllers:
  karakeep:
    type: statefulset

    containers:
      karakeep:
        image:
          repository: ghcr.io/karakeep-app/karakeep
          tag: "{{ .Chart.AppVersion }}"

        env:
          NEXTAUTH_URL:  "{{ .Values.applicationProtocol }}://{{ .Values.applicationHost }}"
          
          DATA_DIR: /data
          MEILI_ADDR: "http://{{ .Release.Name }}-meilisearch:7700"
          BROWSER_WEB_URL: http://{{ .Release.Name }}-chrome:9222

        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}"
          - secretRef:
              name: "{{ .Release.Name }}-meilesearch"
          
        probes:
          liveness:
            enabled: true
            spec:
              initialDelaySeconds: 10
              httpGet:
                path: /api/health
                port: 3000
          readiness:
            enabled: true
            spec:
              initialDelaySeconds: 10
              httpGet:
                path: /api/health
                port: 3000

    statefulset:
      volumeClaimTemplates:
        - name: data
          accessMode: ReadWriteOnce
          size: 2Gi
          globalMounts:
            - path: /data

  chrome:
    containers:
      chrome:
        image:
          repository: gcr.io/zenika-hub/alpine-chrome
          tag: 124

        args:
          - --remote-debugging-address=0.0.0.0
          - --remote-debugging-port=9222
          - --headless
          - --hide-scrollbars
          - --disable-gpu
          - --disable-dev-shm-usage

        probes:
          liveness:
            enabled: true
            spec:
              httpGet:
                path: /
                port: 9222
          readiness:
            enabled: true
            spec:
              httpGet:
                path: /
                port: 9222

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SYS_ADMIN
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000

        resources:
          requests:
            memory: 100Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1000m

service:
  karakeep:
    controller: karakeep
    ports:
      http:
        port: 3000
  chrome:
    controller: chrome
    ports:
      http:
        port: 9222

secrets:
  karakeep:
    enabled: true
    stringData:
      NEXTAUTH_SECRET: "{{ default (randAlphaNum 48) .Values.applicationSecretKey }}"
  meilesearch:
    enabled: true
    stringData:
      MEILI_MASTER_KEY: "{{ default (randAlphaNum 30) .Values.meilisearchMasterKey }}"

ingress:
  karakeep:
    hosts:
      - host: "{{ .Values.applicationHost }}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: karakeep
              port: http

persistence:
  chrome-tmp:
    type: emptyDir
    advancedMounts:
      chrome:
        chrome:
          - path: /tmp
            readonly: false

meilisearch:
  auth:
    existingMasterKeySecret: "{{ .Release.Name }}-meilesearch"
  environment:
    MEILI_ENV: production
  persistence:
    enabled: true
    size: 1Gi
