name: Bug Report
description: Create a report to help us fix bugs & issues in existing supported functionality
labels: [":bug: Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
        Please note that this form is for reporting bugs in existing supported functionality.
        
        If you are reporting something that's not an issue in functionality we've previously supported and/or is simply something different to your expectations, then it may be more appropriate to raise via a feature or support request instead.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detail the steps that would replicate this issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: Provide clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Screenshots or Additional Context
      description: Provide any additional context and screenshots here to help us solve this issue.
    validations:
      required: false
  - type: input
    id: devicedetails
    attributes:
      label: Device Details
      description: |
        If this is an issue that occurs when using the Hoarder interface, please provide details of the device/browser used which presents the reported issue.
      placeholder: (eg. Firefox 97 (64-bit) on Windows 11)
    validations:
      required: false
  - type: input
    id: bsversion
    attributes:
      label: Exact Hoarder Version
      description: This can be found in the bottom left of the page (eg Hoarder v0.18.0)
      placeholder: (eg. v0.18.0)
    validations:
      required: true
