export const MarkdownEditorTheme = {
  code: "bg-[#282A36] text-[#F8F8F2] font-mono block px-4 py-2 my-2 text-sm overflow-x-auto relative rounded-md shadow-sm",
  codeHighlight: {
    atrule: "text-[#8BE9FD]",
    attr: "text-[#8BE9FD]",
    boolean: "text-[#FF79C6]",
    builtin: "text-[#50FA7B]",
    cdata: "text-[#6272A4]",
    char: "text-[#50FA7B]",
    class: "text-[#FF79C6]",
    "class-name": "text-[#FF79C6]",
    comment: "text-[#6272A4]",
    constant: "text-[#FF79C6]",
    deleted: "text-[#FF5555]",
    doctype: "text-[#6272A4]",
    entity: "text-[#FFB86C]",
    function: "text-[#50FA7B]",
    important: "text-[#F1FA8C]",
    inserted: "text-[#50FA7B]",
    keyword: "text-[#FF79C6]",
    namespace: "text-[#F1FA8C]",
    number: "text-[#BD93F9]",
    operator: "text-[#FFB86C]",
    prolog: "text-[#6272A4]",
    property: "text-[#FFB86C]",
    punctuation: "text-[#F8F8F2]",
    regex: "text-[#FF5555]",
    selector: "text-[#50FA7B]",
    string: "text-[#F1FA8C]",
    symbol: "text-[#FF79C6]",
    tag: "text-[#FF79C6]",
    url: "text-[#8BE9FD]",
    variable: "text-[#F1FA8C]",
  },
};
