// there is more than implemented, this come from lexical.dev git
export const MarkdownEditorTheme = {
  ltr: "text-left",
  rtl: "text-right",
  paragraph: "m-0 relative",
  quote:
    "ml-5 my-0 text-sm text-gray-600 border-l-4 border-gray-300 pl-4 dark:text-gray-400 dark:border-gray-600",
  heading: {
    h1: "text-4xl font-bold m-0",
    h2: "text-3xl font-semibold m-0",
    h3: "text-2xl font-medium m-0",
    h4: "text-xl font-normal m-0",
    h5: "text-lg font-light m-0",
    h6: "text-base font-thin m-0",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal pl-4",
    ul: "list-disc pl-4",
    listitem: "ml-8",
    listitemChecked: "line-through text-gray-600 dark:text-gray-400",
    listitemUnchecked:
      "ml-2 mr-2 pl-6 pr-6 relative outline-none list-none dark:text-gray-300",
  },
  hashtag:
    "bg-blue-100 border-b border-blue-300 dark:bg-blue-900 dark:border-blue-700",
  image: "",
  link: "text-blue-600 no-underline hover:underline cursor-pointer dark:text-blue-400",
  text: {
    bold: "font-bold dark:text-white",
    code: "bg-gray-200 px-1 py-0.5 font-mono text-sm dark:bg-gray-700 dark:text-gray-200",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "text-xs align-sub",
    superscript: "text-xs align-super",
    underline: "underline",
    underlineStrikethrough: "underline line-through",
  },
  code: "bg-gray-200 font-mono block px-4 py-2 text-sm overflow-x-auto relative dark:bg-gray-800 dark:text-gray-200",
  codeHighlight: {
    atrule: "text-blue-600 dark:text-blue-400",
    attr: "text-blue-600 dark:text-blue-400",
    boolean: "text-purple-500 dark:text-purple-400",
    builtin: "text-green-600 dark:text-green-400",
    cdata: "text-gray-500 dark:text-gray-400",
    char: "text-green-600 dark:text-green-400",
    class: "text-pink-600 dark:text-pink-400",
    "class-name": "text-pink-600 dark:text-pink-400",
    comment: "text-gray-500 dark:text-gray-400",
    constant: "text-purple-500 dark:text-purple-400",
    deleted: "text-purple-500 dark:text-purple-400",
    doctype: "text-gray-500 dark:text-gray-400",
    entity: "text-orange-500 dark:text-orange-400",
    function: "text-pink-600 dark:text-pink-400",
    important: "text-yellow-500 dark:text-yellow-400",
    inserted: "text-green-600 dark:text-green-400",
    keyword: "text-blue-600 dark:text-blue-400",
    namespace: "text-yellow-500 dark:text-yellow-400",
    number: "text-purple-500 dark:text-purple-400",
    operator: "text-orange-500 dark:text-orange-400",
    prolog: "text-gray-500 dark:text-gray-400",
    property: "text-purple-500 dark:text-purple-400",
    punctuation: "text-gray-400 dark:text-gray-500",
    regex: "text-yellow-500 dark:text-yellow-400",
    selector: "text-green-600 dark:text-green-400",
    string: "text-green-600 dark:text-green-400",
    symbol: "text-purple-500 dark:text-purple-400",
    tag: "text-purple-500 dark:text-purple-400",
    url: "text-orange-500 dark:text-orange-400",
    variable: "text-yellow-500 dark:text-yellow-400",
  },
  characterLimit: "inline bg-red-200 dark:bg-red-700",
  mark: "bg-yellow-100 border-b-2 border-yellow-300 dark:bg-yellow-800 dark:border-yellow-600",
  markOverlap:
    "bg-yellow-300 border-b-2 border-yellow-500 dark:bg-yellow-600 dark:border-yellow-400",
  embedBlock: {
    base: "select-none",
    focus: "outline outline-2 outline-blue-500",
  },
  layoutContainer: "grid gap-2 my-2",
  layoutItem:
    "border border-dashed border-gray-300 px-4 py-2 dark:border-gray-600",
  hr: "border-none my-4 cursor-pointer",
  hrSelected:
    "outline outline-2 outline-blue-500 select-none dark:outline-blue-400",
  specialText: "bg-yellow-300 font-bold dark:bg-yellow-600 dark:text-black",
};
