apiVersion: v1
kind: ConfigMap
metadata:
  name: hoarder-env
data:
  .env: |
    # Add the content of your .env file here
    HOARDER_VERSION=release
    # Use `openssl rand -base64 36` to generate these random strings
    NEXTAUTH_SECRET=super_random_string
    MEILI_MASTER_KEY=another_random_string
    NEXTAUTH_URL=http://localhost:3000
