name: Extension Release Build

on:
  push:
    tags:
      - 'extension/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build the extension (chrome)
        working-directory: apps/browser-extension
        run: pnpm run build --outDir dist-chrome

      - name: Build the extension (firefox)
        env:
          VITE_BUILD_FIREFOX: true
        working-directory: apps/browser-extension
        run: pnpm run build --outDir dist-firefox

      - name: Upload Extension Archive (chrome)
        uses: actions/upload-artifact@v4
        with:
          name: karakeep-extension-chrome
          path: apps/browser-extension/dist-chrome/*

      - name: Upload Extension Archive (firefox)
        uses: actions/upload-artifact@v4
        with:
          name: karakeep-extension-firefox
          path: apps/browser-extension/dist-firefox/*
