name: Publish MCP Package to npm
on:
  push:
    tags:
      # This is a glob pattern not a regex
      - 'mcp/v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build MCP
        run: pnpm build
        working-directory: apps/mcp

      - run: pnpm publish --access public --no-git-checks
        working-directory: apps/mcp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

