name: opencode

on:
  issue_comment:
    types: [created]

jobs:
  opencode:
    if: |
      github.actor == 'MohamedBassem' && (
        contains(github.event.comment.body, '/oc') ||
        contains(github.event.comment.body, '/opencode')
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run opencode
        uses: sst/opencode/github@latest
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        with:
          model: openrouter/moonshotai/kimi-k2
